# Generated by Django 2.0 on 2020-03-11 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackerApp', '0003_auto_20200310_2333'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='genre',
            field=models.CharField(choices=[('Maculino', 'M'), ('Femenino', 'F'), ('Otro', 'O')], default='Otro', max_length=9),
        ),
    ]
