# Generated by Django 3.0.4 on 2020-03-11 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackerApp', '0003_auto_20200310_2333'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='profileImage',
            field=models.ImageField(null=True, upload_to='profileImages'),
        ),
    ]
