# Generated by Django 2.0 on 2020-03-11 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackerApp', '0004_userdata_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='description',
            field=models.CharField(default='Descripcion', max_length=200),
        ),
    ]
