# Generated by Django 3.0.4 on 2020-03-11 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackerApp', '0004_userdata_profileimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='profileImage',
            field=models.ImageField(default='/profileImages/default.jpg', upload_to='profileImages'),
        ),
    ]
