# Generated by Django 2.0 on 2020-03-11 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackerApp', '0005_auto_20200311_0124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='genre',
            field=models.CharField(choices=[('Maculino', 'M'), ('Femenino', 'F'), ('Otro', 'O')], default='Otro', max_length=1),
        ),
    ]
