# Generated by Django 3.0.4 on 2020-03-12 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackerApp', '0006_auto_20200311_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='genre',
            field=models.CharField(choices=[('Maculino', 'M'), ('Femenino', 'F'), ('Otro', 'O')], default='Otro', max_length=8),
        ),
    ]
