# Generated by Django 3.0.4 on 2020-03-12 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trackerApp', '0005_auto_20200311_0319'),
        ('trackerApp', '0007_auto_20200312_2139'),
    ]

    operations = [
    ]
