# Generated by Django 2.0 on 2020-03-13 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackerApp', '0008_merge_20200312_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='genre',
            field=models.CharField(choices=[('Masculino', 'M'), ('Femenino', 'F'), ('Otro', 'O')], default='Otro', max_length=9),
        ),
    ]
