# Generated by Django 2.0 on 2020-03-13 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackerApp', '0009_auto_20200313_0043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='description',
            field=models.CharField(default='Descripción', max_length=200),
        ),
    ]
