# Generated by Django 2.0 on 2020-03-25 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trackerApp', '0010_auto_20200313_2343'),
        ('trackerApp', '0011_loanrequest'),
    ]

    operations = [
    ]
